language: go

os:
  - linux

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
 - sudo add-apt-repository ppa:ubuntu-lxc/daily -y
 - sudo apt-get install -qq libapparmor-dev libcap-dev libseccomp-dev python3-dev python3-setuptools docbook2x libgnutls-dev liblua5.2-dev libselinux1-dev libcgmanager-dev liblxc1 lxc-dev

install:
  - go get gopkg.in/lxc/go-lxc.v2

script:
  - "make all"
  - "make test"
  - "make test-race"
  - "make test-unprivileged"
  - "make test-unprivileged-race"
  - "make cover"

notifications:
  webhooks: https://linuxcontainers.org/webhook-lxcbot/
